# Generated by Django 5.1.2 on 2025-01-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('position', models.IntegerField(choices=[(1, 'Point Guard'), (2, 'Shooting Guard'), (3, 'Small Forward'), (4, 'Power Forward'), (5, 'Center')])),
                ('season_points', models.IntegerField(default=0)),
                ('season_assists', models.IntegerField(default=0)),
                ('season_off_rebounds', models.IntegerField(default=0)),
                ('season_def_rebounds', models.IntegerField(default=0)),
                ('season_fouls', models.IntegerField(default=0)),
                ('season_steals', models.IntegerField(default=0)),
                ('season_blocks', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head_coach', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='BoxScoreApp.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='BoxScoreApp.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='BoxScoreApp.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team1', to='BoxScoreApp.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team2', to='BoxScoreApp.team'),
        ),
    ]
