# Generated by Django 5.1.2 on 2025-01-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxScoreApp', '0003_remove_game_game_id_game_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergamestats',
            old_name='rebounds',
            new_name='def_rebounds',
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='off_rebounds',
            field=models.IntegerField(default=0),
        ),
    ]
