# Generated by Django 5.1.2 on 2025-01-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxScoreApp', '0004_rename_rebounds_playergamestats_def_rebounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_score',
            field=models.IntegerField(default=0),
        ),
    ]
